export * from './University';
export * from './User';
export * from './Department';
export * from './Course';
export * from './Branch';
export * from './Semester';
export * from './Subject';
export * from './Student';
export * from './Teacher';
